framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(APP_LOCALE)%'
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
